import * as cdk from "aws-cdk-lib";
import * as secrets from "aws-cdk-lib/aws-secretsmanager";
import { Construct } from "constructs";
import type { EnvironmentConfig } from "../config/environments.js";

interface SecretsStackProps extends cdk.StackProps {
  envConfig: EnvironmentConfig;
}

export class SecretsStack extends cdk.Stack {
  public readonly jwtSecretArn: string;
  public readonly jwtSecret: secrets.Secret;

  constructor(scope: Construct, id: string, props: SecretsStackProps) {
    super(scope, id, props);

    const { envConfig } = props;

    // Create a secret for JWT signing
    // The secret value will be auto-generated by AWS Secrets Manager
    // It will be a random 256-bit key suitable for HS256 signing
    this.jwtSecret = new secrets.Secret(this, "jwt-secret", {
      secretName: `archil-io-v2-jwt-secret-${envConfig.stage}`,
      description: "JWT signing secret for archil-io-v2 application",
      generateSecretString: {
        secretStringTemplate: "{}",
        generateStringKey: "secret",
        passwordLength: 32, // 256 bits (32 bytes) for HS256
        excludeCharacters: "\"'\\",
        excludePunctuation: false,
      },
    });

    this.jwtSecretArn = this.jwtSecret.secretArn;

    // Output the secret ARN
    new cdk.CfnOutput(this, "jwt-secret-arn", {
      description: "ARN of the JWT signing secret",
      value: this.jwtSecretArn,
      exportName: `archil-io-v2-jwt-secret-arn-${envConfig.stage}`,
    });
  }
}
